//
// Created by peau_c on 4/12/17.
//

#ifndef CPP_PLAZZA_ICONDITIONALVARIABLE_HPP
#define CPP_PLAZZA_ICONDITIONALVARIABLE_HPP

class IConditionVariable {

};

#endif //CPP_PLAZZA_ICONDITIONALVARIABLE_HPP
